version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: research_api
    ports:
      - "8000:8000"
    volumes:
      - ./app/api:/app/api # For live reload during development
      - ./.env:/app/.env # Mount your .env file
    # environment: # Alternative to mounting .env file
    #   - OPENAI_API_KEY=${OPENAI_API_KEY}
    #   - TAVILY_API_KEY=${TAVILY_API_KEY}
    networks:
      - research_net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: research_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./app/frontend:/app/frontend # For live reload during development
    depends_on:
      - api
    networks:
      - research_net
    # Note: In frontend/app.py, FASTAPI_URL should be "http://api:8000/research"
    # because 'api' is the service name in this docker-compose network.
    # For local dev without docker-compose for frontend, it's "http://localhost:8000"

networks:
  research_net:
    driver: bridge